[BOUNTY] Add: Lear room
ss220club/Paradise pull request #102
Opened 2023-05-03 16:48 UTC by SAADf603

## Описание
https://github.com/ss220club/Paradise/pull/66 после решения конфликтов и правок от валлата

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/1097181193939730453/1100736026483367936

2023-05-03 18:38 UTC, Vallat requested changes

2023-05-03 18:38 UTC, Vallat commented on code/game/objects/items/weapons/grenades/custom_grenades.dm
> +	B1.reagents.add_reagent_list("space_drugs" = 25,"lsd" = 25, "potassium" = 25)
А че не компилируем да, а я и проебаться могу 🐀 
```suggestion
	B1.reagents.add_reagent_list(list("space_drugs" = 25,"lsd" = 25, "potassium" = 25))
```

2023-05-03 18:38 UTC, Vallat commented on code/game/objects/items/weapons/grenades/custom_grenades.dm
> +	B2.reagents.add_reagent_list("phosphorus" = 25, "sugar" = 25)
```suggestion
	B2.reagents.add_reagent_list(list("phosphorus" = 25, "sugar" = 25))
```

2023-05-03 18:38 UTC, Vallat commented on code/game/objects/items/weapons/grenades/custom_grenades.dm
> +	B1.reagents.add_reagent_list("ethanol" = 75,"potassium" = 25)
```suggestion
	B1.reagents.add_reagent_list(list("ethanol" = 75,"potassium" = 25))
```

2023-05-03 18:38 UTC, Vallat commented on code/game/objects/items/weapons/grenades/custom_grenades.dm
> +	B2.reagents.add_reagent_list("phosphorus" = 25, "sugar" = 25, "ethanol" = 25)
```suggestion
	B2.reagents.add_reagent_list(list("phosphorus" = 25, "sugar" = 25, "ethanol" = 25))
```

2023-05-03 18:38 UTC, Vallat commented on code/game/objects/items/weapons/grenades/custom_grenades.dm
> +	B1.reagents.add_reagent_list("glycerol" = 30, "sacid" = 15) // todo: someone says NG is overpowered, test.
```suggestion
	B1.reagents.add_reagent_list(list("glycerol" = 30, "sacid" = 15)) // todo: someone says NG is overpowered, test.
```

2023-05-03 18:38 UTC, Vallat commented on code/game/objects/items/weapons/grenades/custom_grenades.dm
> +	B2.reagents.add_reagent_list("sacid" = 15, "facid" = 30)
```suggestion
	B2.reagents.add_reagent_list(list("sacid" = 15, "facid" = 30))
```

2023-05-03 18:38 UTC, Vallat commented on code/game/objects/items/weapons/grenades/custom_grenades.dm
> +	B1.reagents.add_reagent_list("aluminium" = 10, "cola" = 15, "oxygen" = 15, "chlorine" = 10)
```suggestion
	B1.reagents.add_reagent_list(list("aluminium" = 10, "cola" = 15, "oxygen" = 15, "chlorine" = 10))
```

2023-05-03 18:38 UTC, Vallat commented on code/game/objects/items/weapons/grenades/custom_grenades.dm
> +	B2.reagents.add_reagent_list("phosphorus" = 15, "potassium" = 10, "sulfur" = 10)
```suggestion
	B2.reagents.add_reagent_list(list("phosphorus" = 15, "potassium" = 10, "sulfur" = 10))
```

2023-05-04 01:38 UTC, SAADf603 commented
:xdd:

2023-05-04 06:15 UTC, Vallat requested changes

2023-05-04 06:15 UTC, Vallat commented on code/game/objects/items/weapons/grenades/custom_grenades.dm
> +	B1.reagents.add_reagent_list("hell_water" = 80, "sugar" = 20)
А тут тоже я менять буду?
```suggestion
	B1.reagents.add_reagent_list(list("hell_water" = 80, "sugar" = 20))
```

2023-05-04 06:15 UTC, Vallat commented on code/game/objects/items/weapons/grenades/custom_grenades.dm
> +	B2.reagents.add_reagent_list("hell_water" = 60, "potassium" = 20, "phosphorus" = 20)
```suggestion
	B2.reagents.add_reagent_list(list("hell_water" = 60, "potassium" = 20, "phosphorus" = 20))
```

2023-05-08 13:52 UTC, Vallat approved these changes

2023-05-15 11:30 UTC, closed without merging