Dying now connects you to SkyRat
ss220club/Paradise pull request #127
Opened 2023-05-21 15:26 UTC by ImJustKisik

Where you can play with fellow more friendly furry players

2023-05-21 18:42 UTC, Furrior commented on code/modules/mob/living/death.dm
> +		client << link("byond://136.243.82.223:4003")
Выноси в конфиг айпи и включение этой функции.

2023-05-22 16:20 UTC, Furrior requested changes

2023-05-22 16:20 UTC, Furrior commented on code/controllers/configuration.dm
> +	var/enable_furry_trap = TRUE
По умолчанию должно быть выключено

2023-05-22 16:20 UTC, Furrior commented on code/controllers/configuration.dm
> +					config.enable_furry_trap = 1
1 -> TRUE

2023-05-22 16:20 UTC, Furrior commented on config/example/config.txt
> +
Выключай оба по умолчанию и пустую строку в конце файла оставляй

2023-05-22 16:33 UTC, Furrior commented on code/controllers/configuration.dm
> +	var/furrytrapserver
furrytrapserver -> furry_trap_server

2023-05-22 16:34 UTC, Furrior commented on config/example/config.txt
> +FURRYTRAPSERVER byond://136.243.82.223:4003
А это че не закоментил?

2023-05-22 16:35 UTC, ImJustKisik commented on config/example/config.txt
> +FURRYTRAPSERVER byond://136.243.82.223:4003
Чтобы там по дефолту был айпишник скайрата

2023-06-12 20:53 UTC, Furrior commented on code/modules/admin/admin_verbs.dm
> +	if(!check_rights(R_ADMIN))
Надо на R_SERVER проверять

2023-06-17 05:04 UTC, TrashDoxx commented
Идейно спизжено у меня, осуждаю.

2023-07-24 23:33 UTC, closed without merging