[FEAT] new animates googly eyes + food mutate
ss220club/Paradise pull request #213
Opened 2023-07-17 17:07 UTC by PhantornRU

## Описание
Анимированные объекты получают новый пак глаз. Всегда бесили эти однотипные глаза. Так гораздо лучше.
Также если повар вновь сварит отвратительное блюдо, у него есть маленький шанс что оно мутирует и нападет на него.

## Демонстрация изменений

Маг заколдовал интерьер:
![image](https://github.com/ss220club/Paradise/assets/41479614/b6ac2d25-a144-4fb3-aebf-919d66b6a6d0)

Повар приготовил живую яичницу:
![image](https://github.com/ss220club/Paradise/assets/41479614/d667c3cd-9516-4304-97df-d114c7d24297)

Все глаза:
![image](https://github.com/ss220club/Paradise/assets/41479614/8c4b9f70-3968-4955-84bb-99a863d4a553)

2023-07-17 17:23 UTC, Gaxeer requested changes

2023-07-17 17:23 UTC, Gaxeer commented on code/modules/food_and_drinks/food_mutate.dm
> +	var/list/mutation_reagents = list("mutagen", "mutadone", "neurotoxin", "omnizine", "????") //+ GLOB.rare_medicines.Copy() + GLOB.rare_chemicals.Copy() + GLOB.liver_toxins.Copy()
Сделай этот список глобальным, потому что нам не надо каждый раз создавать список когда вызывается данный прок.

2023-07-17 17:23 UTC, Gaxeer commented on code/modules/food_and_drinks/food_mutate.dm
> +		return TRUE
```suggestion
	var/mutation_chance_holder = mutation_chance
	for(var/datum/reagent/reagent as anything in reagents.reagent_list)
		if(reagent.id in mutation_reagents)
			mutation_chance_holder += reagent.volume

	if(prob(mutation_chance_holder))
		mutate()
		return TRUE
```

2023-07-17 17:23 UTC, Gaxeer commented on code/modules/food_and_drinks/food_mutate.dm
> +	new /mob/living/simple_animal/hostile/mimic/copy(O.loc, O)
```suggestion
	new /mob/living/simple_animal/hostile/mimic/copy(loc, src)
```

2023-07-17 17:23 UTC, Gaxeer commented on code/modules/mob/living/simple_animal/hostile/mimic.dm
> +		googly_eyes = image('icons/mob/mob_eyes.dmi',"eyes[eyes_num]")
```suggestion
		googly_eyes = image('icons/mob/mob_eyes.dmi',"eyes[rand(1, 20)]")
```

2023-07-18 13:50 UTC, Furrior commented on code/modules/food_and_drinks/food_mutate.dm
> +	visible_message("<span class='alert'>[src.name] мутировал!</span>")
src.name -> name

2024-02-29 11:38 UTC, closed without merging