Feat: Awaking now!
ss220club/Paradise pull request #22
Opened 2023-04-25 17:48 UTC by SAADf603

## Описание
Заменяет фразу появления персонажа с "прибыл на станцию" на "вышел из криосна". Добавляет декоративные криоподы на шаттлы прибытия на всех картах. 

## Ссылка на предложение/Причина создания ПР
https://discord.com/channels/1097181193939730453/1099657504750829688

## Демонстрация изменений
![1](https://user-images.githubusercontent.com/110329212/234360040-45177f03-0717-4836-8dcf-190f51ab715b.png)
![2](https://user-images.githubusercontent.com/110329212/234360046-30a918e6-ec45-44f6-9570-068e0f53e510.png)
![Безымянный](https://user-images.githubusercontent.com/110329212/234360047-13ef946a-1640-4edc-990d-36ec9e18238e.png)

2023-04-25 19:00 UTC, Vallat requested changes

2023-04-25 19:00 UTC, Vallat commented on code/game/objects/structures/decor/decor.dm
> +	icon_state = "body_scanner_1-r"
Это делается через дайрекшены, а не отдельным объектом. ПР с обновленными спрайтами уже залит, нужно будет править

2023-04-29 07:35 UTC, SAADf603 commented
@Vallat

2023-04-29 07:40 UTC, Vallat commented
> @Vallat

![image](https://user-images.githubusercontent.com/10997188/235290422-3ac7eedb-29c9-46a0-bb02-995990318d87.png)

2023-04-29 20:21 UTC, SAADf603 commented
мне проще сделать так

2023-04-29 20:21 UTC, closed without merging