feat: Changed AI/Cyborg laws upload
ss220club/Paradise pull request #23
Opened 2023-04-25 17:50 UTC by larentoun

## Описание

Теперь при использовании аплоуда открывается TGUI. Для разблокировки кнопки загрузки законов, необходимо выбрать цель (ИИ/робот), модуль законов и вставить карту (необходим доступ ACCESS_AI_UPLOAD, для киборгов достаточно ACCESS_ROBOTICS).

Процесс смены законов занимает время, а именно:
- платы Purge и Reset = 5 секунд
- стандартные законы = мгновенно, если отсутствует набор законов
- синдикатовская плата = 10 секунд
- все остальные платы = 20 секунд

Синдикатовская плата позволяет игнорировать необходимость наличия карты.

## Ссылка на предложение/Причина создания ПР

[Пройденная предложка](https://discord.com/channels/617003227182792704/755125334097133628/1093824260818079754)
[Предложка по аплоуду киборгов](https://discord.com/channels/617003227182792704/755125334097133628/1096740696863559802)

## Changelog

* Feat: AI/Cyborg upload process changed
* Refactor: Cyborg's upload console is now inherited from AI's upload console
* Feat: TGUI for AI/Cyborg law upload
* Tweak: AI/Cyborgs are now notified not by real_name of law changer, but their ID name

## Демонстрация изменений

![Screenshot_1](https://user-images.githubusercontent.com/31931237/230741510-a2e2b626-c575-4dca-82e2-c3a13b65aa12.png)
![Screenshot_2](https://user-images.githubusercontent.com/31931237/230741513-680229c7-7e24-4aa5-b98a-79f9b2f8e241.png)
![Screenshot_3](https://user-images.githubusercontent.com/31931237/230741514-daf85856-b33a-4633-8639-0d3956e6eac8.png)
![Screenshot_4](https://user-images.githubusercontent.com/31931237/230741517-f9fe59b1-1513-45c7-96a3-60db4c2763ea.png)
![Screenshot_5](https://user-images.githubusercontent.com/31931237/230741518-08fb5ad0-b137-4e9a-8a03-888a7eb33156.png)

2023-04-29 07:06 UTC, Vallat submitted a review, later dismissed

2023-04-29 07:06 UTC, Vallat commented on code/game/objects/items/weapons/AI_modules.dm
> +				to_chat(usr, span_notice("Upload process has started. ETA: [delay/10] seconds."))
```suggestion
				to_chat(usr, span_notice("Upload process has started. ETA: [delay / (1 SECONDS)] seconds."))
```

2023-04-29 07:06 UTC, Vallat commented on code/game/objects/items/weapons/AI_modules.dm
> +		else if(ai.see_in_dark == 0)
```suggestion
		else if(!ai.see_in_dark)
```

2023-04-29 07:06 UTC, Vallat commented on code/game/objects/items/weapons/AI_modules.dm
> +		if(ai.stat == DEAD || ai.control_disabled == 1)
`control_disabled ` это булевое значение
```suggestion
		if(ai.stat == DEAD || ai.control_disabled)
```

2023-04-29 07:06 UTC, Vallat commented on code/game/objects/items/weapons/AI_modules.dm
> +	..()
```suggestion
	. = ..()
```

2023-04-29 10:45 UTC, larentoun commented on code/game/machinery/computer/law.dm
> +		if(!user.put_in_active_hand(installed_module))
Этот прок также вызывается в TGUI, когда игрок хочет вытащить модуль из него.

Добавил логику, что предмет, что был внутри, поместится во вторую руку, если возможно.

2023-04-29 13:29 UTC, lebedev commented on code/game/machinery/computer/law.dm
> +			installed_module.forceMove(get_turf(src))
Может тут лучше сработает `put_in_hands`? Делает то же самое, но одним проком.

2023-04-29 13:31 UTC, lebedev commented on code/game/machinery/computer/law.dm
> +		return
Может быть ситуация, что сработает этот код, и тогда выронится `installed_module` и всё? Может эту проверку стоит переместить в начало прока?

2023-04-29 13:35 UTC, larentoun commented on code/game/machinery/computer/law.dm
> +			installed_module.forceMove(get_turf(src))
Вот он прок, который я пытался вспомнить. Нашел `put_in_any_hands_if_possible`, но знал, что это не то!

2023-04-29 13:36 UTC, lebedev requested changes

2023-04-29 13:36 UTC, lebedev commented on tgui/packages/tgui/interfaces/UploadPanel.js
> +                content={selected_target ? selected_target : 'No target selected'}
```suggestion
                content={selected_target || 'No target selected'}
```
И так же в других подобных местах.

2023-04-29 13:36 UTC, lebedev commented on tgui/packages/tgui/interfaces/UploadPanel.js
> +                selected={selected_target ? true : false}
```suggestion
                selected={selected_target}
```
И так же в других подобных местах.

2023-04-29 13:36 UTC, lebedev commented on tgui/packages/tgui/interfaces/UploadPanel.js
> +              label="Selected Target">
Это оно само так отформатировало? Лучше или в одну строку, или `>` на новой.
```suggestion
            <LabeledList.Item label="Selected Target">
```

2023-04-29 13:36 UTC, lebedev commented on tgui/packages/tgui/interfaces/UploadPanel.js
> +                content={id ? id : (hacked ? '$@!ERR0R!@#' : 'No ID card inserted')}
```suggestion
                content={id || (hacked ? '$@!ERR0R!@#' : 'No ID card inserted')}
```
Чуть меньше тернарников.

2023-04-29 13:37 UTC, larentoun commented on code/game/machinery/computer/law.dm
> +		return
Этот прок также вызывается из TGUI, когда нажимают на слот карты/платы, который как раз-таки просто вытаскивает предмет.

2023-04-29 13:38 UTC, lebedev commented on code/game/machinery/computer/law.dm
> +		return
Давай может код вытаскивания вынесем в отдельный прок и для вытаскивания карты будем использовать только его? А не текущий с неочевидным прерыванием выполнения.

2023-04-29 13:51 UTC, larentoun commented on code/game/machinery/computer/law.dm
> +		return
Так могут быть различные ситуации, тогда нужно разделить один этот прок на три разных:
1. Вызываемся ли мы через клик через ТГУИ (ведь ТГУИ может как и вытаскивать, так и вставлять и заменять всё через одну кнопку)
2. Вытаскиваем предмет
3. Вставляем предмет

Так много проков рождается из-за того, что консолька должна жрать и как без ТГУИ (тык без консоли), как и через ТГУИ (тык по кнопке в ТГУИ консоли)

Текущая логика, как по мне, проста
1. Если уже внутри есть модуль, убираем его
2. Если модуль в руке куклы корректный, то:
3. Убираем его у куклы
4. Вставляем в консоль модуль

2023-04-29 14:00 UTC, lebedev commented on code/game/machinery/computer/law.dm
> +		return
Что насчет вынос убирания в отдельный прок? Если нужно убрать карту, то вызываем прок типа "remove_module", а если в руке есть модуль, то вызываем типа "replace_module", который внутри вызывает "remove_module"

2023-04-29 14:02 UTC, lebedev commented on code/game/machinery/computer/law.dm
> +		if(!user.put_in_hands(installed_module))
Перепроверь, пожалуйста, что он работает. Потому что судя по описанию, он пытается положить предмет в руки или дропает его на землю. То есть код можно еще упростить потенциально. Хотя прок лучше переименовать в какой-нибудь "try_put_in_hands_or_drop"

2023-04-29 14:04 UTC, lebedev commented on tgui/packages/tgui/interfaces/UploadPanel.js
> +                disabled={!selected_target || !new_law || (hacked ? false : !id)}
```suggestion
                disabled={!selected_target || !new_law || (!hacked && !id)}
```
Чуть покороче

2023-04-29 14:08 UTC, lebedev commented on code/game/objects/items/weapons/AI_modules.dm
>  		var/obj/machinery/computer/aiupload/comp = C
```suggestion
	var/obj/machinery/computer/aiupload/comp = C
	if(!istype(C))
		return	
```
Давай здесь "early return" с уменьшением отступа всего последующего кода.

2023-04-29 14:10 UTC, lebedev commented on code/game/objects/items/weapons/AI_modules.dm
> +/obj/item/aiModule/proc/install(obj/machinery/computer/C, new_name = "Unknown")
```suggestion
/obj/item/aiModule/proc/install(obj/machinery/computer/aiupload/comp, new_name = "Unknown")
```
Может сразу в проке и ожидать нужный тип?

2023-04-29 18:59 UTC, larentoun commented on code/game/machinery/computer/law.dm
> +		if(!user.put_in_hands(installed_module))
Нет, мне нужно, чтобы предмет вылазил на турфе консоли, как по мне, звучит и выглядит логичнее, чем появляться под игроком

2023-06-27 12:55 UTC, Furrior approved these changes

2023-06-27 12:56 UTC, merged