feat: Thirst meter
ss220club/Paradise pull request #24
Opened 2023-04-25 17:51 UTC by larentoun

## Зависит от конфига
Значение: HYDRATION_ENABLED, по умолчанию выключено

## Описание

Добавить жажду на сервер, которая работает по аналогии с едой, но восстанавливается от жидкостей.
Тратится на 25% быстрее, чем еда. Имеет те же пороговые значения, что и еда.

Пока что имеются следующие балансные решения:
При питье одного полного стакана (50u):
- Питье воды - полное восстановление (+500)
- Обычная жидкость - с красного до синего (+300)
- Холодные напитки (сода, лёд, тоники и прочие газировки) - с красного до зеленого (+200)
- Алкоголь - с зеленого до синего (+100)
- Еда - по умолчанию, снижает с красного до критического (-50)

Для справки:
- Лимит - 550
- Синие - 550
- Зеленое - 450
- Желтое - 350
- Оранжевое - 250
- Красное - 150
- Красное, критическое - 100

Также:
* Вампиры не нуждаются в воде.
* Генокрады при поглощении жертвы восстанавливают себе воду.
* Заклинание мага на снижение еды, также снижает и воду.
* Добавлен следующий текст в осмотре игрока, когда у него обезвоживание: "... looks very thirsty."
* Следующие расы не имеют жажды: абдукторы, големы, КПБ, плазмамены, шедоулинги и шедоу, скелеты, воксы и греи.
* Рвота также тратит 30 единиц воды, или на 1.5 больше, чем потеря еды, в зависимости от того, где больше уйдет.

Имеются следующие алерты при нехватке воды:
"Thirsty" (оранжевый уровень) - "Some water would be good right about now."
"Dehydrated" (красный уровень) - "You're severely dehydrated. The thirst pains make moving around a chore."

При нехватке воды, также появляется болезнь "Dehydration", со следующим описанием: "The patient has low water levels". Cured by: "Providing any form of non-ethanol drinkable liquids."

Удален один слот алертов.

## Изменения для прайма, включается через конфиг `water_poison`
* Также, можно получить отравление, если вода была взята и выпита из кранов, туалетов, с ведер уборщика и тд.
* Шанс на отравление: 5% при глотке. Один стакан в 30u - примерно 26% шанс отравления, пять стаканов в 30u - примрено 78% шанс на отравление.
* Вода может быть очищена с помощью угля.
* Эши не могут отравиться.

## Ссылка на предложение/Причина создания ПР

[Предложка пройдена](https://discord.com/channels/617003227182792704/755125334097133628/1093366098524651620)

## Демонстрация изменений

![image](https://user-images.githubusercontent.com/31931237/229225807-1d26bc61-ad31-4a51-81b0-8439dee7124c.png)

![image](https://user-images.githubusercontent.com/31931237/230653350-706b75d6-8292-41e8-a990-eb3d506f1541.png)
![image](https://user-images.githubusercontent.com/31931237/230653360-4afcd5c9-3891-4d14-bd53-99e900440992.png)
![image](https://user-images.githubusercontent.com/31931237/230653375-9c88b137-7a59-427d-bf9f-7c95306136e9.png)
![image](https://user-images.githubusercontent.com/31931237/230653397-9a817e1b-de8f-412c-8f95-2119a451c216.png)

2023-04-29 06:44 UTC, Vallat requested changes
Даже при выключении фичи с жадой через конфиг на худ всё равно добавляется индикатор жажды. Так не пойдёт.

2023-04-29 09:05 UTC, larentoun commented
> Даже при выключении фичи с жадой через конфиг на худ всё равно добавляется индикатор жажды. Так не пойдёт.

Интересно, помнится, проверял. Пойду еще раз проверю.

2023-04-29 09:47 UTC, larentoun commented
> Даже при выключении фичи с жадой через конфиг на худ всё равно добавляется индикатор жажды. Так не пойдёт.

Если добавить значение в конфиге, оно наоборот включает жажду. Значения по умолчанию в примере конфига - это то, что идет на мейны в таком состоянии. Если оно закомментировано, значит, мейнам это не нужно.

2023-05-04 01:48 UTC, TrashDoxx commented
С каждым днём станция становится ближе к Луфу и дальше от Господа.

2023-05-04 01:49 UTC, TrashDoxx commented
Правда я не особо понимаю, зачем это нужно.

2023-05-04 01:50 UTC, TrashDoxx commented
Хотя тот же вопрос можно задать и про механику голода в станции, так что плевать.

2023-06-27 12:39 UTC, closed without merging