Feat: lonenuke
ss220club/Paradise pull request #35
Opened 2023-04-26 14:58 UTC by Furrior

## Описание
Добавляет новый ивент: оперативник-одиночка

2023-04-26 18:55 UTC, Vallat requested changes

2023-04-26 18:55 UTC, Vallat commented on code/game/gamemodes/nuclear/lone.dm
> +		nuke_code = "Код будет сообщен позже."
Позже - это когда? Может, лучше стоит его сгенерировать в случае отстутствия? Да и может ли вообще такое произойти?
А еще, ты просто присваиваешь строку переданной в функцию переменной, по сути это абсолютно ничего не делает. Выглядит бесполезно

2023-04-26 18:55 UTC, Vallat commented on code/game/gamemodes/nuclear/lone.dm
> +		return FALSE
Соблюдаем `early returns` концепт, пожалуйста
```suggestion
	if(!length(candidates))
		return FALSE
    var/mob/dead/observer/selected = pick(candidates)
    var/mob/living/carbon/human/new_character = makeBody(selected)
    new_character.loc = get_turf(locate("landmark*Syndicate-Spawn"))
    var/datum/mind/operative_mind = new_character.mind
    SSticker.mode.create_syndicate(operative_mind)
    var/mob/living/carbon/human/operative = operative_mind.current
    
    SSticker.mode.syndicates += operative_mind
    SSticker.mode.update_synd_icons_added(operative_mind)
    operative.real_name = "[syndicate_name()] Lone Operative"
    operative_mind.special_role = SPECIAL_ROLE_NUKEOPS
    operative_mind.assigned_role = SPECIAL_ROLE_NUKEOPS
    SSticker.mode.forge_syndicate_objectives(operative_mind)
    SSticker.mode.greet_syndicate(operative_mind)
    
    SSticker.mode.equip_syndicate(operative)
    store_nuke_code(operative_mind, assign_nuke())
    SSticker.mode.update_syndicate_id(operative_mind, TRUE)
    
    var/additional_tk = max(0, (GLOB.player_list.len - 30)*2)
    var/obj/item/radio/uplink/Uplink = locate() in operative.back
    if(istype(Uplink))
	    Uplink.hidden_uplink.uplink_owner = "[operative.key]"
	    Uplink.hidden_uplink.uses = 20 + additional_tk
    
    return TRUE
```

2023-04-26 18:55 UTC, Vallat commented on code/game/gamemodes/nuclear/lone.dm
> +		new_character.loc = get_turf(locate("landmark*Syndicate-Spawn"))
Нельзя так делать. Используй `forceMove()`. Искать по тагу ландмарки тоже ахуенно плохая идея. Организуй прямую ссылку на массив/единичный ландмарк

2023-04-26 18:55 UTC, Vallat commented on code/game/gamemodes/nuclear/lone.dm
> +	processing = 0
```suggestion
	processing = FALSE
```

2023-04-26 18:55 UTC, Vallat commented on code/game/gamemodes/nuclear/lone.dm
> +		addtimer(CALLBACK(src, .proc/make_operative), 30 SECONDS)
Может стоит вызывать эту же функцию, а не функцию созданая оперативника? Вдруг игроков станет меньше?

2023-04-26 18:55 UTC, Vallat commented on code/game/gamemodes/nuclear/lone.dm
> +	var/obj/machinery/nuclearbomb/nuke = locate()
Абсолютно ужасная идея искать бомбу ПО ВСЕМУ МИРУ. Ты буквально проходишь по всем атомам и датумам в игре. Так **нельзя** делать. На нюку должна быть прямая ссылка, генерируемая при её инициализации.

2023-04-26 19:05 UTC, Furrior commented on code/game/gamemodes/nuclear/lone.dm
> +		addtimer(CALLBACK(src, .proc/make_operative), 30 SECONDS)
В аналогичных местах такая же конструкция. Тут суть в том, что бы повторить попытку только еще один раз

2023-04-26 19:15 UTC, Furrior commented on code/game/gamemodes/nuclear/lone.dm
> +		addtimer(CALLBACK(src, .proc/make_operative), 30 SECONDS)
В аналогичных местах такая же конструкция. Тут суть в том, что бы повторить попытку только еще один раз

2023-04-26 19:58 UTC, Vallat requested changes

2023-04-26 19:58 UTC, Vallat commented on code/game/gamemodes/nuclear/lone.dm
> +		stack_trace("Station self-destruct not found during lone op team creation.")
На этом моменте функция оборвётся, последующее обнуление переменной не имеет смысла. Лучше предусмотреть логику работы всего режима целиком в этом случае. Если ядерной боеголовки нет - какой смысл в спавне оперативника?

2023-04-26 19:58 UTC, Vallat commented on code/game/gamemodes/nuclear/lone.dm
> +			stack_trace("Syndicate landmark found not on a turf: [syndicate_spawn.type] on [isnull(syndicate_spawn.loc) ? "null" : syndicate_spawn.loc.type]")
На этот моменте вся функция `get_nuke_spawn_loc` оборвётся и вернёт null, отправив оперативника в небытие. Уверен, что это запланированное поведение?

2023-04-26 19:58 UTC, Vallat commented on code/game/gamemodes/nuclear/lone.dm
> +	if(istype(Uplink))
```suggestion
	var/obj/item/radio/uplink/uplink = locate() in operative.back
	if(istype(uplink))
```

2023-04-27 00:08 UTC, lebedev requested changes

2023-04-27 00:08 UTC, lebedev commented on code/game/gamemodes/nuclear/lone.dm
> +	return nuke_code
```suggestion
	var/obj/machinery/nuclearbomb/nuke = locate() in GLOB.machines
	if(!nuke)
		return null

	if(nuke.r_code == "ADMIN")
		nuke.r_code = rand(10000, 99999)

	return nuke.r_code
```

2023-04-27 00:08 UTC, lebedev commented on code/game/gamemodes/nuclear/lone.dm
> +	var/obj/item/radio/uplink/uplink = locate() in operative.back
Это работает для обоих типов аплинка? И в пда, и в наушнике?

2023-04-27 00:08 UTC, lebedev commented on code/game/gamemodes/nuclear/lone.dm
> +	if(istype(uplink))
А что если по какой-то причине не будет найден аплинк?

2023-04-27 00:08 UTC, lebedev commented on code/game/gamemodes/nuclear/lone.dm
> +	var/additional_tk = max(0, (GLOB.player_list.len - 30)*2)
При 130 игроках оперативнику дало бы 200 дополнительных ТК, верно?

2023-04-27 07:20 UTC, Vallat commented on code/game/gamemodes/nuclear/lone.dm
> +	if(isnull(spawn_loc) || isnull(nuke_code) || !length(candidates))
Подтверждаю

2023-04-27 07:21 UTC, Vallat commented on code/game/gamemodes/nuclear/lone.dm
> +		possible_spawns += get_turf(syndicate_spawn)
`continue` лучше оставить, со второй частью правки согласен. Соблюдаем `early returns`, так лучше читается

2023-04-27 07:22 UTC, Vallat commented on code/game/gamemodes/nuclear/lone.dm
> +/datum/event/operative/proc/get_nuke_spawn_loc()
Название желательно сменить, поддерживаю

2023-04-27 07:23 UTC, Vallat commented on code/game/gamemodes/nuclear/lone.dm
> +	var/obj/item/radio/uplink/uplink = locate() in operative.back
Там спавнится отдельный аплинк-предмет, в рюкзак. Он его и ищет в рюкзаке

2023-04-27 07:24 UTC, Vallat commented on code/game/gamemodes/nuclear/lone.dm
> +	var/additional_tk = max(0, (GLOB.player_list.len - 30)*2)
Верно, оперативник у нас один. Думаю, при 130 игроках такое количество ТК вполне разумно. Да и войну он объявить не может

2023-04-27 10:00 UTC, lebedev commented on code/game/gamemodes/nuclear/lone.dm
> +	var/additional_tk = max(0, (GLOB.player_list.len - 30)*2)
👌

2023-04-27 10:00 UTC, lebedev commented on code/game/gamemodes/nuclear/lone.dm
> +	var/obj/item/radio/uplink/uplink = locate() in operative.back
👌

2023-04-27 10:07 UTC, lebedev commented on code/game/gamemodes/nuclear/lone.dm
> +		possible_spawns += get_turf(syndicate_spawn)
Предлагаю таки без `continue`, так как строка кода в цикле всего одна.

2023-04-27 12:56 UTC, Furrior commented on code/game/gamemodes/nuclear/lone.dm
> +	if(istype(uplink))
Ну, в теории, он всегда там должен быть, но, на случай, если кто то зачем то поменяет прок одевание оперативников, поставлю тогда генерацию нового. На пол, опять же, на случай, если кто то зачем то начудит со слотами, чтоб быть уверенным, что точно загенерит аплинк.

2023-04-27 12:59 UTC, lebedev commented on code/game/gamemodes/nuclear/lone.dm
> +	if(isnull(spawn_loc) || isnull(nuke_code) || !length(candidates))
Я за второй вариант. В целом, лучше писать более кратко, но только если это не вредит читабельности. Первый вариант хуже тем, что пока дочитаешь до `length(candidates)`, можно отвлечься/забыть, что в начале было отрицание, и придется глазами туда-сюда бегать несколько раз. Вообще, если говорить о читабельности, то лучше вообще вместо `!length(candidates)` явно писать `length(candidates) == 0`, но, к сожалению, явный вариант вроде как медленнее работает.

2023-04-27 13:03 UTC, lebedev commented on code/game/gamemodes/nuclear/lone.dm
> +/datum/event/operative/proc/get_nuke_spawn_loc()
Вообще предлагаю укоротить до `pick_spawn_loc`. По пути из контекста понятно, что это спавн лока для оперативника.

2023-04-27 13:24 UTC, Gaxeer commented on code/game/gamemodes/nuclear/lone.dm
> +	if(length(GLOB.player_list) < 30)
на всякий случай напишу, чтобы не забыл: вынеси `30` в дефайн или создай в конфиге проперти для минимального количества людей для старта нюки и бери инфу оттуда

2023-04-27 16:00 UTC, Vallat commented on code/game/gamemodes/nuclear/lone.dm
> +		stack_trace("Lone operative spawned without an uplink. Spawning one.")
Заменить выброс рантайма на месседж админам/дебаг лог

2023-04-27 16:22 UTC, Vallat commented on code/game/gamemodes/nuclear/lone.dm
> +		stack_trace("Lone operative spawned without an uplink. Spawning one.")
Я крыса 🐀

2023-04-27 16:23 UTC, Vallat approved these changes

2023-04-27 17:11 UTC, merged