feat: (Cyberiad) Med remap
ss220club/Paradise pull request #37
Opened 2023-04-26 16:38 UTC by Aylong220

## Описание
Вся инфа тут - https://discord.com/channels/1097181193939730453/1097543419586428989/1100799038699356251

## Ссылка на предложение/Причина создания ПР
Повышение удобства, улучшение внешнего вида, наведение порядков.

## Демонстрация изменений
![MedNew](https://user-images.githubusercontent.com/69762909/234643727-68b23ba2-adfe-4834-b521-478a6f9ca27d.png)

2023-04-26 16:46 UTC, Aylong220 commented
Без понятия что там у механика, я его не трогал
![image](https://user-images.githubusercontent.com/69762909/234645878-35447612-8a92-4f55-950c-6f76dd226893.png)
![image](https://user-images.githubusercontent.com/69762909/234645916-14e22810-4a0f-4448-b70c-f8db473e7f43.png)

2023-04-26 17:01 UTC, dj-34 commented
![image](https://user-images.githubusercontent.com/20109643/234649146-d3141f7a-befb-4f6a-aa36-362b532d162f.png)
![image](https://user-images.githubusercontent.com/20109643/234649229-ffb78fcc-b2d6-4254-9430-0b472238ea73.png)

Ты джокер? Верни механику риг

2023-04-26 17:06 UTC, Aylong220 commented
> 

Лол, как он удалился если я там не трогал KEKW

2023-04-26 18:56 UTC, Vallat commented
В двойной хирургии капельницы и мониторы лучше поменять местами, вроде просили же это сделать в дискорде еще

2023-04-26 19:10 UTC, Aylong220 commented
> В двойной хирургии капельницы и мониторы лучше поменять местами, вроде просили же это сделать в дискорде еще

Я и хотел так сделать, но тогда трубы будут проходить под мониторами.
Если проложить их иначе то будет не симметрично и спагетти.

2023-04-26 19:13 UTC, Vallat commented
Не вижу проблемы в ремаппинге труб не под мониторами, а под капельницами и с заворотом 
![image](https://user-images.githubusercontent.com/10997188/234679114-ff66c3d9-6eb1-4aed-9a1c-2dd1457f34e2.png)

2023-04-26 19:21 UTC, Aylong220 commented
> 

так и делал, может просто мой внутренний перфекционист останавливал, ладно, сделаю так

2023-04-28 18:03 UTC, Vallat commented
Раз ПР более не в драфте, финальный вид карты можно увидеть?

2023-04-28 18:09 UTC, dj-34 commented
> > Раз ПР более не в драфте, финальный вид карты можно увидеть?
> > UPD: Извиняюсь, вижу что обновил в посте. Было бы неплохо про это написать)
> 
> В дискорде это написал, а насчёт обновления, я после каждой правки пикчу обновляю)

Префабами не какал?

2023-04-28 18:11 UTC, Aylong220 commented
> Префабами не какал?

Проверял несколько раз, было немного накаконо, прибрал.

2023-04-28 18:11 UTC, dj-34 approved these changes
Верю на слово

2023-04-28 19:22 UTC, Vallat commented
Жду аппрува от @SAADf603

2023-04-29 02:30 UTC, Aylong220 commented
![Screenshot_20230429-052443_Chrome.jpg](https://user-images.githubusercontent.com/69762909/235279553-8c6b937e-7d11-4776-810d-96a3fae156c3.jpg)

Небольшой косяк, часов через 12 починю

2023-04-29 08:22 UTC, SAADf603 requested changes
Часть 1.
Общая претензия к скрберам и ветнам, которые либо сами находятся не в прямом доступе либо трубы к ним проходят под чем-то. Трубы должно быть ЛЕГКО ВОССТАНОВИТЬ, не разбирая перед этим объекты, на разбор которых требуется больше одного действия. Раз уж решил делать 2 гриндера, то нужна перестановка в химии
В холле под цифрой 2 нужно сделать симметрию. 
Со всех окон убрать плакаты. Во-первых они будут мешать ремонту, во вторых у них opacity = 0, то есть ты будешь видеть через них, что ИЦ тупо.
![Безымянный](https://user-images.githubusercontent.com/110329212/235292307-a0767a48-a29f-4403-aa7e-1118ef5eb2bd.png)

2023-04-29 08:55 UTC, SAADf603 requested changes
Часть 2.
Всё то же по вентам и скраберам.
![2023 04 29-16 39 19](https://user-images.githubusercontent.com/110329212/235294212-5551a031-5323-4a93-83b0-71ceae3b7b1e.png)

2023-04-29 09:21 UTC, SAADf603 requested changes
Последняя часть.
![2023 04 29-16 56 33](https://user-images.githubusercontent.com/110329212/235295274-d24a69d3-d983-43a7-b27d-01bcb75c46f2.png)
![Безымянный](https://user-images.githubusercontent.com/110329212/235295406-1c4b4a61-4e5b-4312-b64a-b45ce4677a5f.png)

2023-04-29 22:31 UTC, dj-34 approved these changes
Вроде порядок

2023-05-02 16:17 UTC, Vallat commented
@Aylong220 Фикси конфликт и в принципе всё, я так понял от @SAADf603 больше правок нет

2023-05-02 17:46 UTC, Vallat approved these changes

2023-05-02 17:46 UTC, merged