Feat: Space Dragon
ss220club/Paradise pull request #58
Opened 2023-04-28 23:24 UTC by larentoun

## Описание

Порт Space Dragon с ТГ. Является мид-раунд мажорным ивентом с весом 20 (такой же, как и у пауков).

TODO:
- Рефакторнуть пиксель-шифт для больших мобов со сдвигом
- Понять, что за фильтры и как их есть
- Понять, что за `move_to` у `carp rift`
- Рефакторнуть облачка текста, рунчат и ду-афтер в зависимости от размера моба (выглядит плохо на драконе)

## Ссылка на предложение/Причина создания ПР

[Одобрено, ссылка на обсуждение](https://discord.com/channels/1097181193939730453/1100141573762715648)

2023-04-29 12:50 UTC, larentoun commented
Остался перевод pepechil

2023-04-29 12:56 UTC, larentoun commented
Думаю, ревью можно открыть и сейчас, перевод можно будет докинуть в процессе ревью

2023-04-30 00:10 UTC, PhantornRU commented on code/modules/space_dragon/action.dm
> +	desc = "Другие всё еще видят вас гигантом."
"Всё еще"? Там прямое действо, так и ебашь напрямую.
"Другие увидят вас гигантом."

2023-04-30 00:13 UTC, PhantornRU commented on code/modules/space_dragon/antag.dm
> +					Но сейчас, мы лицезреем нарушителей, что борются против наших клыков с помощью немыслимой магии; их логова мелькают в глубине космоса, как маленькие огоньки.\n\
"Но сейчас, мы лицезреем нарушителей, что борются против наших клыков с помощью немыслимой магии"
опять двадцать пять. По описанию ты сделал так, будто они борются против магов. На деле же это ИХ немыслимая магия и их зубы.

2023-04-30 00:15 UTC, PhantornRU commented on code/modules/space_dragon/antag.dm
> +	to_chat(owner.current, span_boldwarning("У вас имеется пять минут, чтобы найти безопасное место для создания первого разрыва. Если вы не успеете этого сделать, вы вернетесь в бездну, из которой вы п
Этого сделать... Вы вы вы...
> Если не успеете, вас вернет в бездну, из которой вы пришли.

2023-04-30 00:16 UTC, PhantornRU commented on code/modules/space_dragon/antag.dm
> +	GLOB.command_announcement.Announce("Огромное число биологических объектов направляется к [station_name()] с высокой скоростью. \
Почему биологических, если речь идет о "формах жизней"?

2023-04-30 00:20 UTC, PhantornRU commented on code/modules/space_dragon/antag.dm
> +	Оставшемуся экипажу рекомендуется эвакуироваться как можно скорее...", "Центральное Командование: Наблюдение за дикой природой")
>"Центральное Командование: Наблюдение за дикой природой"
Из названия оно превратились в действие. Не стоит так делать.
Лучше изменить под: "Отдел Исследования Диких Форм Жизни Центрального Командования"

2023-04-30 00:21 UTC, PhantornRU commented on code/modules/space_dragon/antag.dm
> +		parts += "<span class='redtext big'>[name] - успех! Космические карпы вернули контроль над территорией станции!</span>"
над территорией расположения станции.

2023-04-30 00:22 UTC, PhantornRU commented on code/modules/space_dragon/antag.dm
> +		parts += "<span class='redtext big'>The [name] - провал!</span>"
The космический дракон - провал!

Убери THE. Замени "успех" и "провал" на "преуспел" и "провалился". Но точно не существительные.

2023-04-30 00:22 UTC, PhantornRU commented on code/modules/space_dragon/antag.dm
> +	explanation_text = "Защищайте разлом, чтобы призвать больше карпов."
Защищайте разлом призыва карпов.

2023-04-30 00:24 UTC, PhantornRU commented on code/modules/space_dragon/carp.dm
> +	desc = "Создает малый разлом карпов, который позволяет перемещаться на малое расстояние."
Открывает разлом, не создает. Выше тоже это стоит поправить.

Открывает карп-разлом, позволяющий перемещаться на малые расстояния.

2023-04-30 00:24 UTC, PhantornRU commented on code/modules/space_dragon/carp.dm
> +		to_chat(owner, span_warning("Нет выхода из разлома!"))
Невозможно выйти!

2023-04-30 00:25 UTC, PhantornRU commented on code/modules/space_dragon/carp_rift.dm
> +	desc = "Создает разлом, который призывает орды космических карпов"
Создает разлом призыва орды космических карпов

2023-04-30 00:26 UTC, PhantornRU commented on code/modules/space_dragon/carp_rift.dm
> +		to_chat(owner, span_warning("Вы не можете создать разлом здесь! Попробуйте создать где-то в безопасном месте на станции!"))
опять "открыть", не "создать". Еще и дубликат в следующем же положении... Это для верности, если человек идиот и не понимает что делает?

Невозможно открыть разлом здесь!

2023-04-30 00:26 UTC, PhantornRU commented on code/modules/space_dragon/carp_rift.dm
> +	to_chat(owner, span_notice("Вы начинаете создавать разлом..."))
тоже самое

2023-04-30 00:27 UTC, PhantornRU commented on code/modules/space_dragon/carp_rift.dm
> +			to_chat(owner, span_warning("Вы уже создали разлом на этой территории! Вы должны создать его где-то ещё!"))
тоже самое

2023-04-30 00:27 UTC, PhantornRU commented on code/modules/space_dragon/carp_rift.dm
> +		to_chat(owner, span_warning("Вы не можете создать разлом здесь! Для него нужен пол!"))
тоже самое. Но теперь не пол, а поверхность.

2023-04-30 00:28 UTC, PhantornRU commented on code/modules/space_dragon/carp_rift.dm
> +	notify_ghosts("Космический дракон создал разлом!", source = new_rift, action = NOTIFY_FOLLOW, flashwindow = FALSE, title = "Открытие разлома Карпов")
тоже самое. 

Prevent - не допустите. Так будет точнее.

2023-04-30 00:28 UTC, PhantornRU commented on code/modules/space_dragon/carp_rift.dm
> +	desc = "Разлом, похожий на тот, который позволяет космическим карпам перемещаться на огромные расстояния."
чиво? Всмысле "похожий на тот"?

2023-04-30 00:29 UTC, PhantornRU commented on code/modules/space_dragon/carp_rift.dm
> +		. += span_notice("В этом разломе находится [carp_stored] карпов, которые могут появиться для призраков.")
"для вселения призраков"

2023-04-30 00:29 UTC, PhantornRU commented on code/modules/space_dragon/carp_rift.dm
> +		. += span_warning("Этот разлом полностью заряжен. Теперь, этот разлом может перемещать гораздо большее количество карпов, чем обычно.")
разлом разлом разлом на разломе позволяет разлому разломить разломом

2023-04-30 00:30 UTC, PhantornRU commented on code/modules/space_dragon/carp_rift.dm
> +			to_chat(dragon.owner.current, span_boldwarning("Разлом был уничтожен! Вы провалили свою задачу, и депрессия одолевает вас"))
депрессия то тут откуда? Даже в оригинале слабость, ослабевание. Да хоть нереализовавшимся. Но точно не депрессия.

2023-04-30 00:31 UTC, PhantornRU commented on code/modules/space_dragon/carp_rift.dm
> +		GLOB.command_announcement.Announce("Разлом создает неествественно большой поток энергии в зоне [initial(A.name)]. Остановите его любой ценой!", "Центральное Командование: Наблюдение за дикой природ
также как и выше с оповещением

2023-04-30 00:31 UTC, PhantornRU commented on code/modules/space_dragon/carp_rift.dm
> +			to_chat(user, span_warning("Вы уже появлялилсь карпом из этого разлома! Пожалуйста, ожидайте избытка карпов или следующего разлома!"))
>появлялилсь

2023-04-30 00:32 UTC, PhantornRU commented on code/modules/space_dragon/carp_rift.dm
> +	to_chat(newcarp, span_boldwarning("Вы прибыли, чтобы помочь космическому дракону защищать разломы. Не подвергайте опасности миссию и защищайте разломы любой ценой!"))
"опасности миссию"... Очень плохое сочетание. 
Да хоть "не отходите от поставленных целей"

2023-04-30 00:33 UTC, PhantornRU commented on code/modules/space_dragon/event.dm
> +		GLOB.command_announcement.Announce("Зафиксирован большой поток органической энергии вблизи станции [station_name()]. Пожалуйста, ожидайте.", "ВНИМАНИЕ: НЕОПОЗНАННЫЕ ФОРМЫ ЖИЗНИ.")
Даже тут у тебя неопознанные формы жизни. А выше ты об этом забыл.

2023-04-30 00:33 UTC, PhantornRU commented on code/modules/space_dragon/event.dm
> +	var/list/candidates = SSghost_spawns.poll_candidates("Вы хотите занять роль Космического дракона?", ROLE_SPACE_DRAGON, TRUE, source = /mob/living/simple_animal/hostile/space_dragon)
почему не с большой буквы?
Космический Дракон - название. Если ты делаешь из этого вид, то тогда "космический" тоже убери заглавную букву

2023-04-30 00:35 UTC, PhantornRU commented on code/modules/space_dragon/mob.dm
> +	desc = "Мерзкое существо, схожее с классом левиафан, которое летает самым неестественным способом. Внешне, немного похоже на космического карпа."
Не мерзкое, а "ужасное" будет получше и по смыслу.

Схож внешне с космическим карпом.

2023-04-30 00:36 UTC, PhantornRU commented on code/modules/space_dragon/mob.dm
> +	deathmessage = "визжит, их крылья превращаются в пыль, и оно падает на пол, в глазах угасает жизнь."
"ИХ" крылья 
А затем: "ОНО"

2023-04-30 00:36 UTC, PhantornRU commented on code/modules/space_dragon/mob.dm
> +		to_chat(src, span_warning("Вы почти укусили себя, но вы вовремя остановились."))
Вы вы вы вы вы.

УБери ВЫ после "но"

2023-04-30 00:36 UTC, PhantornRU commented on code/modules/space_dragon/mob.dm
> +	to_chat(src, span_notice("Ваше имя теперь - [span_name("[chosen_name]")], устрашающий Космический дракон."))
опять название или вид?

2023-04-30 00:37 UTC, PhantornRU commented on code/modules/space_dragon/mob.dm
> +		to_chat(src, span_danger("Этот цвет некорректен - он не слишком яркий."))
не яркий, а светлый будет корректней?

2023-04-30 00:37 UTC, PhantornRU commented on code/modules/space_dragon/mob.dm
> +		to_chat(L, span_userdanger("Вы попали под огненное дыхание [src]!"))
Вы попали под огненное дыхание [src.name]

2023-04-30 00:38 UTC, PhantornRU requested changes
Просмотрел перевод

2023-04-30 10:29 UTC, larentoun commented on code/modules/space_dragon/antag.dm
> +					Но сейчас, мы лицезреем нарушителей, что борются против наших клыков с помощью немыслимой магии; их логова мелькают в глубине космоса, как маленькие огоньки.\n\
Разве не для карпов оружие людей является магией?

2023-04-30 10:30 UTC, larentoun commented on code/modules/space_dragon/antag.dm
> +	GLOB.command_announcement.Announce("Огромное число биологических объектов направляется к [station_name()] с высокой скоростью. \
Скопипастил с других переводов наших "lifeforms", у той же миграции карпов или бореров

2023-04-30 10:31 UTC, larentoun commented on code/modules/space_dragon/antag.dm
> +	Оставшемуся экипажу рекомендуется эвакуироваться как можно скорее...", "Центральное Командование: Наблюдение за дикой природой")
Не слишком длинно получается?

2023-04-30 10:32 UTC, larentoun commented on code/modules/space_dragon/antag.dm
> +		parts += "<span class='redtext big'>The [name] - провал!</span>"
А, да, не заметил в прошлый раз

2023-04-30 10:34 UTC, larentoun commented on code/modules/space_dragon/carp.dm
> +	desc = "Создает малый разлом карпов, который позволяет перемещаться на малое расстояние."
Получается, как, что дырку создают, или дырка в пространстве появляется? Порталы тоже открывают?

2023-04-30 10:35 UTC, larentoun commented on code/modules/space_dragon/carp.dm
> +		to_chat(owner, span_warning("Нет выхода из разлома!"))
Тут как раз сообщение о том, что созданный портал не имеет доступных точек выхода

2023-04-30 10:37 UTC, larentoun commented on code/modules/space_dragon/carp_rift.dm
> +	desc = "Разлом, похожий на тот, который позволяет космическим карпам перемещаться на огромные расстояния."
У космических карпов есть мини-телепорт, и вот, этот разлом похож на мини-телепорт

2023-04-30 10:38 UTC, larentoun commented on code/modules/space_dragon/carp_rift.dm
> +			to_chat(dragon.owner.current, span_boldwarning("Разлом был уничтожен! Вы провалили свою задачу, и депрессия одолевает вас"))
Просто взял из описания обилки, что депрессия приходит. Да, ослабевание лучше подходит

2023-04-30 10:39 UTC, larentoun commented on code/modules/space_dragon/carp_rift.dm
> +	to_chat(newcarp, span_boldwarning("Вы прибыли, чтобы помочь космическому дракону защищать разломы. Не подвергайте опасности миссию и защищайте разломы любой ценой!"))
" Не подвергайте риску миссию и защищайте разломы любой ценой" ?

2023-04-30 10:40 UTC, larentoun commented on code/modules/space_dragon/event.dm
> +		GLOB.command_announcement.Announce("Зафиксирован большой поток органической энергии вблизи станции [station_name()]. Пожалуйста, ожидайте.", "ВНИМАНИЕ: НЕОПОЗНАННЫЕ ФОРМЫ ЖИЗНИ.")
Опять же, у нас и так и так в коде перевод писали

2023-04-30 10:41 UTC, larentoun commented on code/modules/space_dragon/mob.dm
> +	deathmessage = "визжит, их крылья превращаются в пыль, и оно падает на пол, в глазах угасает жизнь."
А как тогда в среднем роде обозвать, "его крылья"?

2023-04-30 10:42 UTC, larentoun commented on code/modules/space_dragon/mob.dm
> +		to_chat(L, span_userdanger("Вы попали под огненное дыхание [src]!"))
По умолчанию берется `.name` , если не указано иначе.

2023-04-30 10:46 UTC, lebedev commented on code/modules/space_dragon/mob.dm
> +		to_chat(L, span_userdanger("Вы попали под огненное дыхание [src]!"))
По умолчанию добавляется the

2023-05-01 11:37 UTC, Vallat requested changes
Выписал то, что заметил при первом просмотре. Посмотрю потом еще раз

2023-05-01 11:44 UTC, larentoun commented on code/modules/mob/living/living.dm
> +							visible_message(span_danger("[H] не поспевает за [src] и с грохотом падает на пол!"))
https://github.com/ss220club/Paradise/pull/71 , согласовано

2023-05-01 11:45 UTC, Vallat commented on code/modules/mob/living/living.dm
> +							visible_message(span_danger("[H] не поспевает за [src] и с грохотом падает на пол!"))
Так оно идёт отдельным ПРом, почему оно находится здесь?

2023-05-01 11:50 UTC, larentoun commented on code/modules/mob/living/living.dm
> +							visible_message(span_danger("[H] не поспевает за [src] и с грохотом падает на пол!"))
И там, и тут один и тот же коммит. Тут находится, чтобы сигналы не ругались

2023-05-02 15:48 UTC, Vallat requested changes

2023-05-02 15:48 UTC, Vallat commented on code/modules/space_dragon/antag.dm
> +	return ..()
```suggestion
/datum/antagonist/space_dragon/Destroy()
	rift_list = null
	carp = null
	dragon = null
	QDEL_NULL(rift_ability)
	return ..()
```

2023-05-02 16:23 UTC, Vallat commented on code/_onclick/hud/other_mobs.dm
> -	static_inventory += mymob.pullin
А понял куда

2023-05-02 17:07 UTC, Vallat approved these changes

2023-05-02 17:07 UTC, merged