Tweak: loneop nerf 2
ss220club/Paradise pull request #72
Opened 2023-04-30 15:18 UTC by Furrior

## Описание
Увеличено минимальное кол во игроков для ивента.
Теперь лоноп не может покупать подкрепление.

2023-04-30 16:56 UTC, lebedev requested changes

2023-04-30 16:56 UTC, lebedev commented on code/game/gamemodes/nuclear/lone.dm
>  		uplink = new(get_turf(operative))
Лучше не спавнить аплинк в куклу. Потому что если по какой-то причине у него будет забит рюкзак, аплинк останется contents в куклы и не будет доступен.
```suggestion
	var/obj/item/radio/uplink/nuclear/lone/uplink = new(get_turf(operative))
	if(operative.back)
		operative.equip_to_slot_or_del(uplink, slot_in_backpack)
	else
		stack_trace("Lone operative spawned without a backpack. Spawning uplink on the floor.")
```

2023-04-30 16:58 UTC, lebedev commented on code/game/gamemodes/nuclear/lone.dm
>  		uplink = new(get_turf(operative))
А, хотя стоп. У тебя же `equip_to_slot_or_del`. То есть при забитом рюкзаке аплинк удалится. Ну дела.

2023-04-30 18:07 UTC, Furrior commented on code/game/gamemodes/nuclear/lone.dm
>  		uplink = new(get_turf(operative))
Выбрал другой прок, должно покрывать любую ситуацию

2023-05-02 15:59 UTC, Furrior commented on code/game/gamemodes/nuclear/lone.dm
> +	uplink.equip_to_best_slot(operative, ignore_source_loc = TRUE)
Если так сделать, то аплинк всегда на полу будет спавнится, тк equip_to_best_slot не работает, если предмет не в руке(для обхода этого и было сделано изменение этого самого прока)

2023-05-02 16:04 UTC, Vallat commented on code/game/gamemodes/nuclear/lone.dm
> +	uplink.equip_to_best_slot(operative, ignore_source_loc = TRUE)
Упс, не та функция, вот так должно быть

2023-05-02 16:22 UTC, Vallat approved these changes

2023-05-02 16:22 UTC, merged